export const BAILEYS_METHODS = [
    'appPatch',
    'sendPresenceUpdate',
    'presenceSubscribe',
    'profilePictureUrl',
    'onWhatsApp',
    'fetchBlocklist',
    'fetchPrivacySettings',
    'fetchStatus',
    'updateProfilePicture',
    'updateBlockStatus',
    'resyncAppState',
    'chatModify',
    'assertSessions',
    'relayMessage',
    'refreshMediaConn',
    'sendMessage',
    'groupMetadata',
    'groupCreate',
    'groupLeave',
    'groupUpdateSubject',
    'groupParticipantsUpdate',
    'groupInviteCode',
    'groupToggleEphemeral',
    'groupSettingUpdate',
    'groupFetchAllParticipating',
    'ws',
    'authState',
    'user',
    'generateMessageTag',
    'query',
    'waitForMessage',
    'waitForSocketOpen',
    'sendRawMessage',
    'sendNode',
    'logout',
    'end',
    'waitForConnectionUpdate'
] as const

export const NEKOS_DOT_LIFE = 'https://nekos.life/api/v2/img/'
